# Created 07/18/2025 by Paulina Salazar.

# All categories of service providers stored in the database.
categories:
- accountants
- airductcleaning
- appliances
- appraisalservices
- audiovisualequipmentrental
- auto
- auto_detailing
- autocustomization
- autodamageassessment
- autoelectric
- autoglass
- autoinsurance
- autopartssupplies
- autorepair
- autosecurity
- autoupholstery
- barbers
- bike_repair_maintenance
- bikerepair
- bikes
- bikeshop
- carpet_cleaning
- carpeting
- carpetinstallation
- carwash
- carwindowtinting
- copyshops
- datarecovery
- dryclean
- drycleaninglaundry
- drywall
- electricians
- electronics
- electronicsrepair
- financialadvising
- financialservices
- flooring
- furniturerepair
- hairstylists
- handyman
- hardware
- homeandgarden
- homeappliancerepair
- homecleaning
- homeinsurance
- homenetworkinstall
- homeservices
- insulationinstallation
- insurance
- isps
- itservices
- junkremovalandhauling
- kitchenandbath
- laundromat
- laundryservices
- lawnservices
- lighting
- locksmiths
- mobilephones
- motorcycledealers
- motorcyclepartsandsupplies
- motorcyclerepair
- motorepairs
- movers
- naturalgassuppliers
- notaries
- opticians
- packingservices
- passportvisaservices
- pet_sitting
- pet_training
- petadoption
- petcremation
- petinsurance
- petservices
- petwasteremoval
- plumbing
- poolcleaners
- poolservice
- roofing
- roofinspectors
- screen_printing_tshirt_printing
- screenprinting
- securitysystems
- selfstorage
- sewingalterations
- shoerepair
- shredding
- snowremoval
- softwaredevelopment
- stereo_installation
- taxlaw
- taxoffice
- taxservices
- televisionserviceproviders
- tenantlaw
- translationservices
- transmissionrepair
- university_housing
- utilities
- vehiclewraps
- watch_repair
- waterheaterinstallrepair
- web_design
- wheelrimrepair
- wildlifecontrol
- windowsinstallation
- windowwashing
- windshieldinstallrepair
